#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const CLIENT_DIR = path.resolve(__dirname, "..");
const REPO_DIR = path.resolve(CLIENT_DIR, "..");
const SERVER_DIR = path.join(REPO_DIR, "server");

const API_DIR = path.join(CLIENT_DIR, "src", "lib", "api");
const OPENAPI_JSON = path.join(API_DIR, "openapi.json");
const TYPES_TS = path.join(API_DIR, "types.ts");

function sh(cmd, args, cwd) {
  const res = spawnSync(cmd, args, { cwd, stdio: "inherit" });
  if (res.status !== 0) process.exit(res.status ?? 1);
}

function biomeFormat(paths) {
  const biome = path.join(CLIENT_DIR, "node_modules", ".bin", "biome");
  try {
    readFileSync(biome);
  } catch {
    process.stderr.write(
      "warning: biome not found; skipping formatting for generated files\n"
    );
    return;
  }

  sh(biome, ["format", "--write", ...paths], CLIENT_DIR);
}

function genStubTypesTs() {
  return `// This file is generated by \`npm run gen:api\`.
// Install dependencies and re-run to get fully typed API helpers:
//   npm i
//   npm run gen:api
export type paths = Record<string, unknown>;
`;
}

function genTypesTs() {
  const openapiTypescript = path.join(
    CLIENT_DIR,
    "node_modules",
    ".bin",
    "openapi-typescript"
  );

  try {
    readFileSync(openapiTypescript);
  } catch {
    process.stderr.write(
      "warning: openapi-typescript not found; generating a stub types.ts\n"
    );
    writeFileSync(TYPES_TS, genStubTypesTs(), "utf-8");
    return;
  }

  sh(openapiTypescript, [OPENAPI_JSON, "--output", TYPES_TS], CLIENT_DIR);
}

function main() {
  mkdirSync(API_DIR, { recursive: true });

  sh(
    "cargo",
    [
      "run",
      "--quiet",
      "--bin",
      "openapi_gen",
      "--",
      "--format",
      "json",
      "--output",
      OPENAPI_JSON,
    ],
    SERVER_DIR
  );

  genTypesTs();
  biomeFormat([TYPES_TS]);

  try {
    rmSync(OPENAPI_JSON, { force: true });
  } catch {
    // ignore
  }
}

main();
