/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/callbacks/lnurl-auth": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["lnurlAuthCallback"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/callbacks/open-channel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["openChannel"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/callbacks/withdraw-request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["withdraw"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/channel-request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["channelRequest"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/lnurl-auth-request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["lnurlAuthRequest"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/withdraw-request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["withdrawRequest"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    BitcoinInfo: {
      /**
       * Format: int64
       * @description Current number of blocks.
       */
      blocks: number;
      /** @description Blockchain name (e.g. bitcoin, testnet, regtest). */
      chain: string;
      /**
       * Format: int64
       * @description Number of connections to peers.
       */
      connections: number;
      /**
       * Format: int64
       * @description Current number of headers.
       */
      headers: number;
      /** @description Whether bitcoind is in initial block download. */
      initial_block_download: boolean;
      /** @description Overall status of the bitcoind JSON-RPC connection. */
      status: components["schemas"]["BitcoinStatus"];
      /** @description Bitcoind subversion string. */
      subversion: string;
      /**
       * Format: double
       * @description Verification progress (0.0 to 1.0).
       */
      verification_progress: number;
      /**
       * Format: int64
       * @description Bitcoind version number.
       */
      version: number;
      /** @description Any warnings reported by bitcoind. */
      warnings?: string | null;
    };
    /** @enum {string} */
    BitcoinStatus: "ok" | "unreachable" | "notconfigured";
    ChannelRequestResponse: {
      /** @description Second-level URL to trigger OpenChannel */
      callback: string;
      /** @description Wallet identifier */
      k1: string;
      /** @description Type of request, must be "channelRequest" */
      tag: string;
      /** @description Remote node address of form node_key@ip_address:port_number */
      uri: string;
    };
    HealthResponse: {
      /** @description Overall status of the bitcoind JSON-RPC connection. */
      bitcoin: components["schemas"]["BitcoinInfo"];
      /** @description Overall status of the CoreLightning node. */
      lightning: components["schemas"]["LightningInfo"];
      /**
       * Format: int64
       * @description Maximum withdrawable amount in millisatoshis.
       */
      max_withdrawable_msat: number;
      /**
       * Format: int64
       * @description Minimum withdrawable amount in millisatoshis.
       */
      min_withdrawable_msat: number;
      /** @description Warning message when bitcoind is not in sync (may be absent). */
      warning_bitcoind_sync?: string | null;
      /** @description Warning message when lightningd is not in sync (may be absent). */
      warning_lightningd_sync?: string | null;
    };
    IssueWithdrawRequest: {
      /** Format: int64 */
      amount?: number | null;
      destination: string;
      k1: string;
    };
    IssueWithdrawResponse: {
      psbt: string;
      tx: string;
      txid: string;
    };
    LightningInfo: {
      /** @description Node alias (may be absent). */
      alias?: string | null;
      /** @description CoreLightning version string. */
      cln_version: string;
      /**
       * Format: int32
       * @description Number of active channels.
       */
      num_active_channels: number;
      /**
       * Format: int32
       * @description Number of connected peers.
       */
      num_peers: number;
      /**
       * Format: int32
       * @description Number of pending channels.
       */
      num_pending_channels: number;
      /** @description Node public key (hex). */
      pubkey: string;
      /** @description Human-readable overall status; clients treat ok/healthy/ready as operational. */
      status: components["schemas"]["LightningStatus"];
    };
    /** @enum {string} */
    LightningStatus: "ok" | "syncing";
    LnUrlAuthQuery: {
      /** @description One-time challenge (32 bytes hex) */
      k1: string;
      /** @description Compressed (33-byte) secp256k1 public key hex */
      key: string;
      /** @description DER-hex-encoded ECDSA signature for `k1` (some wallets may use compact 64-byte) */
      sig: string;
    };
    /** @enum {string} */
    LnUrlAuthRequestAction: "register" | "login" | "link" | "auth";
    LnUrlAuthRequestQuery: {
      action?: null | components["schemas"]["LnUrlAuthRequestAction"];
    };
    LnUrlAuthRequestResponse: {
      action?: null | components["schemas"]["LnUrlAuthRequestAction"];
      /** @description Callback URL to be called by the wallet with `sig` and `key` */
      callback: string;
      /** @description (32 bytes hex) One-time challenge */
      k1: string;
      /** @description Type of request, must be "login" per LUD-04 */
      tag: string;
    };
    LnUrlAuthResponse: {
      error?: string | null;
      ok: boolean;
      result?: unknown;
    };
    OpenChannelRequest: {
      /** Format: int64 */
      amount?: number | null;
      announce?: boolean | null;
      k1: string;
      remote_id: string;
    };
    OpenChannelResponse: {
      error?: string | null;
      ok: boolean;
      result?: unknown;
    };
    WithdrawRequestResponse: {
      /** @description Second-level URL to trigger WithdrawCallback */
      callback: string;
      /** @description Default description for the withdrawal invoice */
      defaultDescription: string;
      /** @description Unique identifier for this withdrawal request */
      k1: string;
      /**
       * Format: int64
       * @description Maximum withdrawable amount in millisatoshis
       */
      maxWithdrawable: number;
      /**
       * Format: int64
       * @description Minimum withdrawable amount in millisatoshis
       */
      minWithdrawable: number;
      /** @description Type of request, must be "withdrawRequest" */
      tag: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  lnurlAuthCallback: {
    parameters: {
      query: {
        /** @description Challenge token from /lnurl-auth */
        k1: string;
        /** @description Signature of k1 (hex, compact or DER) */
        sig: string;
        /** @description Signing public key (hex, compressed) */
        key: string;
        /** @description Optional LNURL-auth action */
        action?: string;
        /** @description Optional LNURL-auth tag */
        tag?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description LNURL-auth callback response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LnUrlAuthResponse"];
        };
      };
    };
  };
  openChannel: {
    parameters: {
      query: {
        /** @description One-time token from /channel-request */
        k1: string;
        /** @description Remote node pubkey */
        remote_id: string;
        /** @description Channel funding amount in satoshis */
        amount?: number;
        /** @description Whether to announce channel */
        announce?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Open channel result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OpenChannelResponse"];
        };
      };
    };
  };
  withdraw: {
    parameters: {
      query: {
        /** @description One-time token from /withdraw-request */
        k1: string;
        /** @description Bitcoin address (or other supported withdraw destination) */
        destination: string;
        /** @description Withdraw amount in satoshis */
        amount?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Withdraw result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueWithdrawResponse"];
        };
      };
    };
  };
  channelRequest: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description LNURL Channel Request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChannelRequestResponse"];
        };
      };
      /** @description The CoreLightning node encountered an error */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Gateway and CoreLightning status */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
      /** @description The CoreLightning node encountered an error */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  lnurlAuthRequest: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description LNURL-auth challenge */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LnUrlAuthRequestResponse"];
        };
      };
    };
  };
  withdrawRequest: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description LNURL Withdraw Request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WithdrawRequestResponse"];
        };
      };
    };
  };
}
